Installation facilitation + welcome page population
elvisblanco1993/intern-hub pull request #8
Opened 2023-03-25 00:24 UTC by Elijahx

(1) Removed composer.lock file to help with local execution. (2) Populated welcome page with background image + heading + button for standard desktop dimensions. Possible TODO: scaling for tablet + phone dimensions.

2023-03-25 02:23 UTC, elvisblanco1993 requested changes
Can you please rewrite this using Tailwind CSS?

To get Tailwind working in that page, you can add this before the </head> section of the page:

@vite(['resources/css/app.css', 'resources/js/app.js'])

That'll compile your css once you start applying Tailwind's classes. For the button, you can do:

<x-button>yourtexthere</x-button>

2023-03-29 04:37 UTC, Elijahx commented
Rewrote using tailwind css utility class structure via the second method we discussed. Let me know if anything needs to change.

2023-03-29 14:08 UTC, elvisblanco1993 commented
Looks good. Thank you!

2023-03-29 14:08 UTC, elvisblanco1993 approved these changes

2023-03-29 14:08 UTC, merged